config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  root 'posts#index', as: 'home'
  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true,
                        length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "Shane", password: "1234", only: [:destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:username, :body)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

 def about
   @title = "About Us"
   @content = "This is the About page"
 end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "Shane", password: "1234", except: [:index, :show]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if(@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if(@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
  <div class="card-footer">
    <p class="card card-body bg-light">
      <strong><%= comment.username %>:</strong>
      <%= comment.body %>
      <%= link_to '❌', [comment.post, comment],
                    method: :delete,
                    data: {confirm: 'Are you sure?'},
                    :class => 'btn btn-secondary btn-sm', :style => "width: 3%"%>
    </p>
    </div>
<% end %>

app/views/comments/_form.html.erb
<h3>Add Comment</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger"><%= msg %></div>
  <% end %>
<% end %>
<p>
  <%= f.label :username %><br>
  <%= f.text_field(:username, {:class => 'form-control'}) %><br>
</p>

<p>
  <%= f.label :body %><br>
  <%= f.text_area(:body, {:class => 'form-control'}) %><br>
</p>

<p>
  <%= f.submit({:class => 'btn btn-primary'}) %>
</p>

<% end %>

app/views/layouts/application.html.erb
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <title>Document</title>
</head>
<body>
  <style></style>
  <div class="wrapper">
    <div class="box header">Header</div>
    <div class="box sidebar">Sidebar</div>
    <div class="box content"><%= yield %>
      <br</div>
    <div class="box footer">Footer</div>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class ="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field(:title, {:class => 'form-control'}) %><br>
</p>

<p>
  <%= f.label :body %><br>
  <%= f.text_area(:body, {:class => 'form-control'}) %><br>
</p>

<p>
  <%= f.submit({:class => 'btn btn-primary'}) %>
</p>

<% end %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>

<head><%= stylesheet_link_tag "application", :media => "all" %></head>

<div class="box sidebar">
  <% @posts.each do |post| %>
    <div class="card card-body bg-light">
      <div class="card-header">
      <h4><%= post.title %></h4>
    </div>
    <div class="card-body">
      <p class="card-text"><%= post.body %></p>
      <%= link_to "Read More", post_path(post), :class => 'btn btn-secondary' %>
    </div>
    </div>
    <br>
  <% end %>
</div>

app/views/posts/new.html.erb
  <h1>Add Post</h1>
  <%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |msg| %>
        <div class ="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %><br>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, {:class => 'form-control'}) %><br>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </p>

  <% end %>

app/views/posts/show.html.erb
<div class="card card-body bg-light">
  <div class="card-header">
    <h2><%= @post.title %></h2>
  </div>
  <div class="card-body">
    <p class="card card-body"><%= @post.body %></p>
  </div>
  <%= render 'comments/comments' %>
</div>

<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-primary' %>

<%= link_to "Delete", @post, method: :delete, data: {confirm: 'Are you sure you want to delete this post?'}, :class => 'btn btn-danger' %>
<hr>

<%= render 'comments/form' %>